name: pomodoro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.18.5+1
  flutter_local_notifications: ^12.0.4
  flutter_native_timezone: ^2.0.0
  flutter_picker: ^2.0.5
  flutter_switch: ^0.3.2
  freezed_annotation: <2.1.0
  gap: ^2.0.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.0
  intl: ^0.17.0
  json_serializable: ^6.4.1
  percent_indicator: ^4.0.1
  riverpod_annotation: ^1.0.6
  timezone: ^0.9.0
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: ^2.2.1
  flutter_native_splash: ^2.2.9

  flutter_test:
    sdk: flutter
  freezed: <2.1.1
  hive_generator: ^1.1.3
  import_sorter: ^4.6.0
  pedantic_mono: ^1.20.0
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/pomodoro-768.png
    - assets/images/pomodoro-1152.png
